export const sidebrarLinks = [
    {
        imgURL:"/home.png",
        label:"home",
        route:"/"
    },
    {
        imgURL:"/group.png",
        label:"community",
        route:"/community"
    },
    {
        imgURL:"/database.png",
        label:"collection",
        route:"/collection"
    },
    {
        imgURL:"/promotion.png",
        label:"job",
        route:"/job"
    },
    {
        imgURL:"/user.png",
        label:"profile",
        route:"/profile"
    },
    {
        imgURL:"/price-tag.png",
        label:"tag",
        route:"/tag"
    },
    {
        imgURL:"/question-mark.png",
        label:"ask-question",
        route:"/ask-question"
    },
]
