import "./globals.css";
import ThemeProvider from "../context/Theme";
import Session from "../context/Session";
import { Toaster } from "../components/ui/toaster";

export const metadata = {
  title: "Dev Flow",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="antialiased">
        <Session>
          <ThemeProvider attribute="class" defaultTheme="light">
            {children}
            <Toaster />
          </ThemeProvider>
        </Session>
      </body>
    </html>
  );
}
